import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    id 'application'
    id 'org.jetbrains.kotlin.jvm' version '2.0.0'
}

application {
    mainClass = 'edu.hcmute.buoi_4.Bai01_ClassSanPhamKt'
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

tasks.withType(KotlinCompile).configureEach {
    compilerOptions {
        jvmTarget = JvmTarget.JVM_17
    }
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib"
}
